=== TODOs
* [ ] consume a rest call that returns json
** [x] nasa rest api
**  [ ] find ways to convert between json string and java objects
* [ ] mocking a rest provider
** [ ] wiremock
* [ ] contract driven development without spring
* [x] read properties from a properties file, javaee way
* [ ] generate code using open-api or such


http://www.jsonschema2pojo.org/[json2java]








== Notes
=== A note
==== Some other note
===== Yet another note

https://asciidoctor.org/[asciidoc] +
https://powerman.name/doc/asciidoc[asciidoc cheat sheet]

.This is a title
    for indented paragraph.

.This is some *Java* code
[source,java]
private static final String DELIMITER = "/";

.A note
NOTE::
Some simple note.

[NOTE]
A single-paragraph note.

TIP: tip

IMPORTANT: important

WARNING: warning

CAUTION: caution

.Whatever
----
Some nonsense text.
----

.Whatever
****
Some nonsense text.
****

forced +
line break.

.A table
|==================
|Col1   |Col2   |Col3
|1      |11     |111
|2      |22     |222
|3      |33     |333
|==================

[ditaa, "ditaa-diagram"]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....

http://plantuml.com/guide[plantuml]

[plantuml, diagram-classes, png]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....
